### ISSUE TITLE
NameError: name 'ArgumentParser' is not defined

### ISSUE THREAD

**Issue by loveJasmine** [emansim/text2image#10]
envy@ub1404:~/os_pri/github/text2image$ python mnist-captions/sample-captions.py --model models/mnist-captions.json --weights ..
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "mnist-captions/sample-captions.py", line 42, in <module>
    parser = ArgumentParser()
NameError: name 'ArgumentParser' is not defined
envy@ub1404:~/os_pri/github/text2image$

**Comment by emansim** [comment]
have you imported ArgumentParser from argparse ?
