### ISSUE TITLE
KeyError: 'costFunction'

### ISSUE THREAD

**Issue by loveJasmine** [emansim/text2image#11]
envy@ub1404:~/os_pri/github/text2image$ python coco/sample-captions.py --model coco/models/coco-captions-32x32.json --weights ..
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "coco/sample-captions.py", line 79, in <module>
    costFunctionType = str(model["model"][0]["costFunction"]["type"])
KeyError: 'costFunction'
envy@ub1404:~/os_pri/github/text2image$

**Comment by emansim** [comment]
Interesting.

I am not really sure about --weights .. when you are running it. Can you try removing that and running the script.
