### ISSUE TITLE
Training Models is taking too long

### ISSUE THREAD

**Issue by umerebryx** [emansim/text2image#12]
I am trying to train models defined in coc0-captions-32x32.json but it is taking insane amount of time. There are around 200 epochs and it tool 15 hours to complete just one:

Epoch 0 took 15:17:07.833333

Just wondering is there a way to get it done faster or completing iterations for all 200 epochs is really necessary. Is there a base number I can use to get a minimal working setup. Or if anyone have trained weight files that would really help me out. Thanks

I am using NVIDIA GPU for my test on an AWS instance.

**Comment by emansim** [comment]
You don't need to run the experiments for 200 epochs, the model usually converges after 7-10 epochs.

I lost the reference to the original trained model we used in the paper, but try using these weights 
http://www.cs.toronto.edu/~emansim/cap2im-weights/aligndraw.h5

**Comment by umerebryx** [comment]
Thanks @emansim

**Comment by jtoy** [comment]
@emansim just wondering, what is the longest you have trained it for? have you seen better results from longer training?

**Comment by emansim** [comment]
Don't remember exact number of epochs, but somewhere between 13 and 20 epochs.

Sure the log likelihood will keep improving as you train for more epochs, but not sure whether qualitative results will be better.

**Comment by umerebryx** [comment]
@emansim thanks for all the help, I got it working now, but the output image quality is not that great for the aligndraw.h5 that you provided above. Do you know the number of epochs this was run against so I can have a better guess what number should I set for training my models. Thanks
