### ISSUE TITLE
your .theanorc

### ISSUE THREAD

**Issue by kalloc** [emansim/text2image#5]
Hi.
Thank you for your research!

Sorry, I have problem with testing, can you show your .theanorc?
I got typecasting error:
```
TypeError: Cannot convert Type TensorType(float32, matrix) (of Variable AdvancedSubtensor1.0) into Type TensorType(float64, matrix). You can try to manually convert AdvancedSubtensor1.0 into a TensorType(float64, matrix).
```

**Comment by emansim** [comment]
you need to set floatX to float32

my theanorc looks like this

[global]
base_compiledir = /tmp/%(user)s/theano
floatX = float32
device = cpu
allow_gc = True

[nvcc]
fastmath = True

[scan]
allow_gc = True

[blas]
ldflags = -L/u/emansim/local/lib -lblas

[cuda]
root = /pkgs/cuda-5.5
