### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by loveJasmine** [emansim/text2image#6]
envy@ub1404:~/os_pri/github/text2image$ python coco/alignDraw.py mnist-captions/models/mnist-captions.json
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "coco/alignDraw.py", line 608, in <module>
    train_paths = model["data"]["train"]
KeyError: 'train'
envy@ub1404:~/os_pri/github/text2image$ python coco/alignDraw.py mnist-captions/models/mnist-captions.json
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
Traceback (most recent call last):
  File "coco/alignDraw.py", line 608, in <module>
    train_paths = model["data"]["train"]
KeyError: 'train'
envy@ub1404:~/os_pri/github/text2image$

**Comment by emansim** [comment]
you should be calling this instead
python coco/alignDraw.py coco/models/coco-captions-32x32.json 

you weren't using the right json file since, mnist-captions is a different dataset

**Comment by loveJasmine** [comment]
envy@ub1404:~/os_pri/github/text2image$ python mnist-captions/alignDraw.py mnist-captions/models/mnist-captions.json 
Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN 4007)
(50000, 784) (50000,) (10000, 784) (10000,)
Banned configurations are :
[6, 6, 9, 5, 9, 2, 3, 10, 7, 8, 1, 1]
Train Dataset
(10000, 3600) (10000, 12) [1176, 1197, 1165, 1251, 1288, 1299, 1289, 1335]
mnist-captions/alignDraw.py:337: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if valData != None:
Val Dataset
(10000, 3600) (10000, 12) [1132, 1190, 1183, 1357, 1317, 1345, 1258, 1218]
building gradient function
0:00:13.547572
building train function
0:10:04.190429
Epoch 0 took 0:14:27.302321
Train Results
20.4986621122 980.411366577 1000.91003357
Validation Results
building validate function
0:00:31.926712
20.8608053589 1749.13969482 1770.00049316


Recreated Train Dataset
[1195, 1137, 1165, 1274, 1326, 1350, 1263, 1290]


[ub1404:04315] *** Process received signal ***
[ub1404:04315] Signal: Bus error (7)
[ub1404:04315] Signal code: Non-existant physical address (2)
[ub1404:04315] Failing at address: 0x7feb03f41d40
