### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by xinghedyc** [emansim/text2image#7]
Hi,I set the floatX = float32 already , but I also got the TypeError 
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by emansim** [comment]
interesting
which version of theano are you using ?

**Comment by Wakeupbuddy** [comment]
I got same error here. my version is '0.8.2'.

**Comment by xinghedyc** [comment]
my theano version is 0.8.1

**Comment by emansim** [comment]
I haven't used theano 0.8 yet and all the experiments were run with theano 0.7 version
it looks like the error was introduced in the new theano update.
i will look into it and see what i find.

**Comment by umerebryx** [comment]
I am facing a similar issue.

**Comment by emansim** [comment]
Related thread on how to solve this issue: https://github.com/fchollet/keras/issues/2083
Adding the flag warn_float64=pdb will show where the upcasting to float64 happens.

I would recommend using theano version 0.7 to run the experiments, since there might be other potential changes added to theano 0.8 that could give different results.

**Comment by umerebryx** [comment]
I downgraded to theano 0.7 and issue was resolved. Thanks

@emansim I have opened another [issue](https://github.com/emansim/text2image/issues/12) can please comment on that as well. Will really appreciate your help.
